function fg = fig_setting_default()

fg.pu = get(gcf,'PaperUnits');
fg.pp = get(gcf,'PaperPosition');

set(gcf,...
    'Units',fg.pu,...
    'Position',fg.pp,...
    'PaperPosition', fg.pp,...
    'PaperSize', fg.pp([3:4]),...
    'color', 'w'...
    );
set(gcf, 'PaperPositionMode', 'Auto');
set(gca,...
    'box','off',...
    'layer','top',...
    'TickDir','out');

